# Generated by Django 3.2.4 on 2021-06-30 16:24

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ind_empleado', models.CharField(choices=[('N', 1), ('B', 2), ('F', 3), ('A', 4), ('S', 5), ('X', 0)], default='X', max_length=1)),
                ('sexo', models.CharField(choices=[('V', 0), ('H', 1), ('O', 2)], default='O', max_length=1)),
                ('ind_nuevo', models.IntegerField(choices=[('0', 0), ('1', 1), ('9', 2)], default=2)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', jsonfield.fields.JSONField()),
                ('feature_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.featureset')),
            ],
        ),
    ]
