FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY ./docker/requirements.txt /code/
RUN pip install -r requirements.txt
RUN pip install djangorestframework drf-yasg jsonfield django-import-export django-json-widget
COPY ../. /code/

ENTRYPOINT [ "/bin/bash" ]
CMD [ "./docker/start.sh" ]