FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY ./docker/requirements.txt /code/
RUN pip install -r requirements.txt
RUN pip install djangorestframework drf-yasg
COPY ../. /code/
# RUN python ./api/manage.py makemigrations app
CMD [ "/bin/bash" ]